export async function awaitError(response, expectedMessage) {
  try {
    await response;
  } catch (err) {
    if (err instanceof Error && err.message !== expectedMessage) {
      throw err;
    }
  }
}